3d_keypoint_camera_frame:
- [-0.05489826157587097, 0.004713265640586051, 0.9030831582916857]
- [-0.012558749165256691, 0.018018608692725646, 0.8406032891249244]
- [-0.048901280684662304, -0.028507646759055594, 0.8156925314100856]
bbox_bottom_right_xy: [327, 260]
bbox_top_left_xy: [261, 194]
camera_to_world:
  quaternion: {w: -0.1158451135107951, x: 0.7082329859624331, y: -0.6772402617675701,
      z: 0.16227006843962555}
  translation: {x: 0.2989606370576388, y: -0.008280143681802177, z: 0.8240921843408416}
depth_image_filename: 000000_depth.png
keypoint_pixel_xy_depth:
- [286, 239, 903]
- [311, 247, 840]
- [287, 217, 815]
rgb_image_filename: 000000_rgb.png
timestamp: 1550716705347060911